name: Build and deploy Ionic app to Azure Web App

# IMPORTANT: Before using this workflow, you need to add the following secrets to your repository:
# - FIREBASE_API_KEY: Your Firebase API Key
# - FIREBASE_AUTH_DOMAIN: Your Firebase Auth Domain
# - FIREBASE_PROJECT_ID: Your Firebase Project ID
# - FIREBASE_STORAGE_BUCKET: Your Firebase Storage Bucket
# - FIREBASE_MESSAGING_SENDER_ID: Your Firebase Messaging Sender ID
# - FIREBASE_APP_ID: Your Firebase App ID
# - FIREBASE_MEASUREMENT_ID: Your Firebase Measurement ID
#
# You can add these secrets in your repository settings:
# Settings > Secrets and variables > Actions > New repository secret

on:
  push:
    branches:
      - autentication
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create environment files directly
        run: |
          # Create environment directories if they don't exist
          mkdir -p src/environments
          
          # Create environment.ts directly
          cat > src/environments/environment.ts << EOL
          // src/environments/environment.ts
          export const environment = {
            production: false,
            apiUrl: 'https://ionic-cheese-back.onrender.com/api',
            useEmulators: false,
            firebase: {
              apiKey: "dummy-api-key-for-build",
              authDomain: "dummy-auth-domain-for-build",
              projectId: "dummy-project-id-for-build",
              storageBucket: "dummy-storage-bucket-for-build",
              messagingSenderId: "000000000000",
              appId: "1:000000000000:web:0000000000000000000000",
              measurementId: "G-0000000000",
            },
          };
          EOL
          
          # Create environment.prod.ts directly
          cat > src/environments/environment.prod.ts << EOL
          // src/environments/environment.prod.ts
          export const environment = {
            production: true,
            apiUrl: 'https://ionic-cheese-back.onrender.com/api',
            useEmulators: false,
            firebase: {
              apiKey: "dummy-api-key-for-build",
              authDomain: "dummy-auth-domain-for-build",
              projectId: "dummy-project-id-for-build",
              storageBucket: "dummy-storage-bucket-for-build",
              messagingSenderId: "000000000000",
              appId: "1:000000000000:web:0000000000000000000000",
              measurementId: "G-0000000000",
            },
          };
          EOL
          
          # Show created files
          echo "Created environment.ts file:"
          cat src/environments/environment.ts
          echo ""
          echo "Created environment.prod.ts file:"
          cat src/environments/environment.prod.ts

      - name: Debug environment
        run: |
          echo "Checking environment files:"
          ls -la src/environments/
          echo "Current directory structure:"
          ls -la

      - name: Modify build script
        run: |
          # Create a custom build script that bypasses the config-env.ts script
          echo '#!/bin/bash' > custom-build.sh
          echo 'ionic build --configuration production' >> custom-build.sh
          chmod +x custom-build.sh
          cat custom-build.sh

      - name: Build app for production
        run: ./custom-build.sh
        # Using a custom build script to bypass the config-env.ts dependency

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ionic-app-build
          path: www
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ionic-app-build
          path: www

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0F9D2722DF2D44B0AB3275506E818DB8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0847DB209E4D438697D0ADACAA3379AA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1D6FC8EE1CA84AB0957F563BC6CE5BC2 }}

      - name: Configure web.config for SPA routing
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > www/web.config
          echo '<configuration>' >> www/web.config
          echo '  <system.webServer>' >> www/web.config
          echo '    <rewrite>' >> www/web.config
          echo '      <rules>' >> www/web.config
          echo '        <rule name="Angular Routes" stopProcessing="true">' >> www/web.config
          echo '          <match url=".*" />' >> www/web.config
          echo '          <conditions logicalGrouping="MatchAll">' >> www/web.config
          echo '            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />' >> www/web.config
          echo '            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />' >> www/web.config
          echo '          </conditions>' >> www/web.config
          echo '          <action type="Rewrite" url="/index.html" />' >> www/web.config
          echo '        </rule>' >> www/web.config
          echo '      </rules>' >> www/web.config
          echo '    </rewrite>' >> www/web.config
          echo '    <staticContent>' >> www/web.config
          echo '      <mimeMap fileExtension=".webp" mimeType="image/webp" />' >> www/web.config
          echo '      <mimeMap fileExtension=".json" mimeType="application/json" />' >> www/web.config
          echo '    </staticContent>' >> www/web.config
          echo '  </system.webServer>' >> www/web.config
          echo '</configuration>' >> www/web.config

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "cheese-front"
          slot-name: "Production"
          package: www

      - name: Logout from Azure
        run: az logout
        if: always()
